services:
  app:
    build: .
    container_name: api_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    build: ./database
    container_name: api_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8020:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build:
      context: ./relata-sk-front
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://api_app:3001/api"
    container_name: quasar_web
    depends_on:
      - app
    ports:
      - "9000:80"
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:

networks:
  default:
    name: local-network
    external: true
